### ISSUE TITLE
About the Eq.(4) in the paper

### ISSUE THREAD

**Issue by zfbz** [dahyun-kang/renet#10]
Hi, I'm a beginner.
But I was confused, the implementation of eq.(4) in the code seems to take `F` as input, not `Z` (in the paper).

**Comment by dahyun-kang** [comment]
Hello

Yes, Eq. (4) of the paper is intended to take `F` as an input. Please also refer to equations 2 and 3.
Have a great day!

Best, 
Dahyun

**Comment by zfbz** [comment]
> Hi, I'm a beginner. But I was confused, the implementation of eq.(4) in the code seems to take `F` as input, not `Z` (in the paper).

sorry, it is eq.(7)

**Comment by zfbz** [comment]
> Hello
> 
> Yes, Eq. (4) of the paper is intended to take `F` as an input. Please also refer to equations 2 and 3. Have a great day!
> 
> Best, Dahyun

Thank you for your timely reply! **It is eq.(7)**, not be eq.(4).  >_<

**Comment by dahyun-kang** [comment]
Oh actually you are correct. The z_q in the Eq. 7 comes from average pooling F, not Z.
I'll be revising the manuscript soon.

Thanks for pointing it out!

**Comment by zfbz** [comment]
> Oh actually you are correct. The z_q in the Eq. 7 comes from average pooling F, not Z. I'll be revising the manuscript soon.
> 
> Thanks for pointing it out!

Thank you very much! I have no doubt. ^_^

**Comment by dahyun-kang** [comment]
No problem. Closing the issue.
