### ISSUE TITLE
 the miniimagenet data set you shared can't be accessed

### ISSUE THREAD

**Issue by Up-007** [dahyun-kang/renet#11]
Hello, the miniimagenet data set you shared can't be accessed. Could you share it again? Thank you very much。

**Comment by dahyun-kang** [comment]
Hello,

I've provided a dataset download link from [deepEMD](https://github.com/icoz69/DeepEMD), which I just found the miniImageNet dataset is removed from [their Google drive](https://drive.google.com/drive/folders/1sXJgi9pXo8i3Jj1nk08Sxo6x7dAQjf9u).
You can ask them or refer to [another alternative public dataset provider](https://www.kaggle.com/datasets/arjunashok33/miniimagenet). I didn't check whether it is exactly the same config as the one that I used though, but I presume it should be the same.
Note that the alternative link specified that they didn't resize the image size, while I used 84x84-size images.

Have a great day! :smiley: 

Dahyun

**Comment by Up-007** [comment]
Thank you very much for your reply, which is very helpful to me. Have a good  day!
