### ISSUE TITLE
Inductive or transductive？

### ISSUE THREAD

**Issue by Fancy-sf** [dahyun-kang/renet#6]
In the n-way k-shot( k>1) setting, the attended features of the support set are computed by summing k attended features, which are influenced by the query set. I wonder whether it is an inductive or transductive setting in few-shot learning.

**Comment by dahyun-kang** [comment]
Hello,

Our method is an inductive method in the context of few-shot learning.
Averaging k-shot support image features is a prevalent way to incorporate given few-shot images.

For more information about transductive setups, refer to these papers.

Liu et al., Learning to propagate labels: transductive propagation network for few-shot learning, ICLR'19.
Liu et al., Prototype rectification for few-shot learning, ECCV'20.

Have a great day! :smiley:
