### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by gkgo** [dahyun-kang/renet#7]

**Comment by gkgo** [comment]
Hi, I'm a beginner. When I read your paper, I didn't quite understand the functions of SCR and CCA, and I didn't find any articles about it. How to understand the functions of these two modules?

**Comment by dahyun-kang** [comment]
Hi,

Thank you for your attention!

The motivations and behaviors of those two modules are precisely described in [our paper](https://arxiv.org/abs/2108.09666).
In summary, the high-level concept of each module is to first build a relational context as a correlation and then extract useful representations from it using convolutions.
Each module is implemented in `models/scr.py` and `models/cca.py`.


For your better understanding, here are some insightful papers, which I heavily referred to as well. Their methods take either self-correlations or cross-correlations of images as input data and learn the correlational patterns for corresponding tasks. 

Rocco _et al._, [Neighbourhood Consensus Networks](https://arxiv.org/abs/1810.10510), Neurips'18.
Kwon _et al._, [Learning Self-Similarity in Space and Time as Generalized Motion for Video Action Recognition](https://arxiv.org/abs/2102.07092), ICCV'21.






Have a great day! :smiley:
